SELECT * FROM POKEMONS INNER JOIN POKEMON_TIPOS ON POKEMONS.ID = POKEMON_TIPOS.POKEMON_ID;
SELECT * FROM POKEMONS LEFT JOIN POKEMON_TIPOS ON POKEMONS.ID = POKEMON_TIPOS.POKEMON_ID;
SELECT * FROM POKEMONS LEFT JOIN POKEMON_TIPOS ON POKEMONS.ID = POKEMON_TIPOS.POKEMON_ID WHERE POKEMON_TIPOS.POKEMON_ID IS NULL;
SELECT * FROM POKEMONS RIGHT JOIN POKEMON_TIPOS ON POKEMONS.ID = POKEMON_TIPOS.POKEMON_ID;
SELECT * FROM POKEMONS RIGHT JOIN POKEMON_TIPOS ON POKEMONS.ID = POKEMON_TIPOS.POKEMON_ID WHERE POKEMONS.ID IS NULL;
SELECT * FROM POKEMONS FULL JOIN POKEMON_TIPOS ON POKEMONS.ID = POKEMON_TIPOS.POKEMON_ID;
SELECT * FROM POKEMONS FULL JOIN POKEMON_TIPOS ON POKEMONS.ID = POKEMON_TIPOS.POKEMON_ID WHERE POKEMONS.ID IS NULL OR POKEMON_TIPOS.POKEMON_ID IS NULL;
SELECT J1.FORMA JOGADOR_1, J2.FORMA JOGADOR_2 FROM JOKENPO AS J1 CROSS JOIN JOKENPO AS J2;